services:
  backend:
    build: backend/.
    ports:
      - "8000:8000"
    container_name: casino_backend
    command: sh -c "cd src && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_ENV=dev
