services:
  backend:
    build: backend/.
    ports:
      - "8000:8000"
    container_name: casino_backend
    command: sh -c "cd src && python manage.py migrate && gunicorn --config gunicorn.conf.py core.wsgi:application"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    env_file:
      - .env

volumes:
  postgres_data:
