POST http://127.0.0.1:8000/auth/jwt/login/
Content-Type: application/json

{
  "username": "aldick",
  "password": "12052008Aa!"
}

###
POST http://127.0.0.1:8000/auth/jwt/refresh/
Cookie: refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MjM2NTM1OSwiaWF0IjoxNzYyMjc4OTU5LCJqdGkiOiJiNWRmODQ5MGFmMmI0YTBiODA5OTYxNmQ2ZjNhZDBjYSIsInVzZXJfaWQiOjF9.Qrcgfi3vOGeOxYxl57Z2ifbiBFg2501gh_svyDajjGE

### 
POST http://127.0.0.1:8000/auth/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMjQ4ODc3LCJpYXQiOjE3NjIyNDg1NzcsImp0aSI6IjA5M2Q1MGVkMmJlNTRlZGI4MDRlMWYyNTIzNTZmN2YwIiwidXNlcl9pZCI6MX0.cqlYDUZ1phbjj0R_rUPby6HAHEFgdEtHldRVUAcP9_I

###
GET http://localhost:8000/deposit/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNTk5NjI3LCJpYXQiOjE3NjI1OTg3MjcsImp0aSI6Ijc4NWNjMjViNDk2MDRmMTU4MzNlMGFmMGE0YmU3OGU4IiwidXNlcl9pZCI6MX0.rJEphKzcZrnNgImxfgSqR4TcYdlZlKnlL7WcWA6cBH8

###
POST http://localhost:8000/deposit/?promocode=PERCENT20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzMDA4ODg2LCJpYXQiOjE3NjMwMDc5ODYsImp0aSI6IjQ5MDcyM2I2MGRhMTQ3ODU5NDY1YmE5NGE2MmJjNWRkIiwidXNlcl9pZCI6MX0.vfdcRyEugbBnODxr1_Yi7XUZiSmNUVYR2QFVMXZhMYg
Content-Type: application/json

{
	"deposit": "1000"
}

###
POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
	"username": "aldick",
	"email": "aldick@sigma.tv",
	"password": "12052008Aa!"
}

###
GET http://localhost:8000/auth/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNTAzNTMwLCJpYXQiOjE3NjI1MDI2MzAsImp0aSI6Ijg4MTY3MWQ5NmNiZTRiOWJiMDVmNmUyNGI2YTUwMWZlIiwidXNlcl9pZCI6MX0.bRxbloCWGoPSK7l0_RVr7l-K_NNlLIkBvKUvXmkWYig

###
POST http://localhost:8000/coin-flip/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMjQ0MzAwLCJpYXQiOjE3NjIyNDQwMDAsImp0aSI6ImI0NGY0MWQwMWIwZTQwNmQ4MTMxYmQzYTA0OGQ4YzBlIiwidXNlcl9pZCI6MX0.nKcKoby-l9IzFH8R4Um4JiK0LD1LpgtVXwV1RPCtS6c
Content-Type: application/json

{
  "bet": 10,
  "choice": "heads"
}

###
POST http://localhost:8000/roulette/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMjg2ODQ0LCJpYXQiOjE3NjIyODY1NDQsImp0aSI6ImYwZTFlYTdmMTBmZjQwZDhiZWU5ZjhhMTNkNzJmMDM5IiwidXNlcl9pZCI6MX0.D-o5TivQYzcGMimm4VpOcaHVBAAGQK6VO-GSSKj-ZkM
Content-Type: application/json

[
  {"bet": 100, "bet_type": "color", "bet_value": "red"},
  {"bet": 50, "bet_type": "even_odd", "bet_value": "odd"},
  {"bet": 25, "bet_type": "number", "bet_value": "17"}
]