# Generated by Django 5.2.1 on 2025-11-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_deposithistory_used_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposithistory',
            name='used_promocode',
        ),
    ]
